### ISSUE TITLE
Pre-trained model

### ISSUE THREAD

**Issue by jodyngo** [libiseller/MobileNetV2-dynamicFPN#2]
May you please share the pre-trained model of this network?

**Comment by wenwenaixuexi** [comment]
hello,May you please share the pre-trained model of this network?

**Comment by libiseller** [comment]
Hello, there is no pre-trained model.

**Comment by wenwenaixuexi** [comment]
ok，thanks~



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Stefan ***@***.***&gt;; 
发送时间: 2022年11月3日(星期四) 晚上6:48
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [libiseller/MobileNetV2-dynamicFPN] Pre-trained model (Issue #2)





 
Hello, there is no pre-trained model.
